--- #YAML:1.0
name:               Net-LDAP-Server
version:            0.43
abstract:           LDAP server side protocol handling
author:
    - Alessandro Ranellucci <aar@cpan.org>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Convert::ASN1:  0
    Net::LDAP:      0
resources:
    repository:  git://git@github.com:alexrj/Net-LDAP-Server.git
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.56
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
