#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Net-LDAP-Server
version:      0.3
version_from: lib/Net/LDAP/Server.pm
installdirs:  site
requires:
    Net::LDAP:                     0
    Convert::ASN1:                 0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.12
